---
name: Test
on:
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  test:
    runs-on: blacksmith-2vcpu-ubuntu-2404-arm
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Install gotestsum
        shell: bash
        run: go install gotest.tools/gotestsum@latest
      - name: Test
        shell: bash
        run: gotestsum ./...
